RHAIENG-948: fix(ppc): build failure due to missing protobuf>=4.25.1 in aipcc wheel index
```
+ pip wheel . -w /root/onnx_wheel
...
        ERROR: Could not find a version that satisfies the requirement protobuf>=4.25.1 (from versions: none)
        ERROR: No matching distribution found for protobuf>=4.25.1
        [end of output]
```